steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/swan:base || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/base.Dockerfile',
    '-t', 'swan:base',
    '-t', 'gcr.io/$PROJECT_ID/swan:base',
    '--cache-from', 'gcr.io/$PROJECT_ID/swan:base',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/swan:base']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/swan:latest',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/coverage.Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/swan:coverage',
    '.'
  ]
timeout: 1800s
images: ['gcr.io/$PROJECT_ID/swan:base', 'gcr.io/$PROJECT_ID/swan:latest', 'gcr.io/$PROJECT_ID/swan:coverage']
